apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: controlplanes.arcdata.microsoft.com
spec:
  group: arcdata.microsoft.com 
  version: v1alpha1
  names:
    kind: ControlPlane
    plural: controlplanes
  additionalPrinterColumns:
  - name: Phase
    type: string
    JSONPath: .status.phase
  scope: Namespaced