apiVersion: arcdata.microsoft.com/v1alpha1
kind: ControlPlane
metadata:
    name: controlplane
    namespace: arc
spec:
    adminCredentials: "controller-admin-secret"
    controlPlaneConfig:
        clusterName: arcdatademo
        dockerRegistry: azurearcdata.azurecr.io
        dockerRepository: azure-arc-data
        dockerImageTag: private-preview-mar-2020
        storageClass: standard
        serviceType: LoadBalancer
        controllerPort: 30080
        serviceProxyPort: 30777
        settings:
            billingEnabled: "True"
        dataController:
            displayName: "arcdatademo"
            connectionMode: "disconnected"
            billingMode: "consumption"
            subscription: "513c5156-789d-4ab2-9ef1-175027551332"
            resourceGroup: "ConnectToArc"
            location: "EastUS"
